[package]
name = "online-store"
version = "0.1.0"
edition = "2021"

[dependencies]
solana-program = "2.0.5"
borsh = "1.5.1"
borsh-derive = "1.5.1"

[dev-dependencies]
solana-program-test = "2.0.5"
solana-program = "2.0.5"

[lib]
crate-type = ["cdylib", "lib"]